import type { DiagramConfig, MermaidLook } from '../types'
import type { ThemeVariablesByDiagram } from './mermaidThemeVariables'

export interface ThemePresetDef {
  label: string
  description: string
  vars: ThemeVariablesByDiagram
  configOverrides: Partial<{
    look: MermaidLook
    fontFamily: string
    fontSize: number
    flowchart: Partial<DiagramConfig['flowchart']>
    sequence: Partial<DiagramConfig['sequence']>
    gantt: Partial<DiagramConfig['gantt']>
    xyChart: Partial<{ plotColorPalette: string }>
  }>
}

export const THEME_PRESET_DEFS: Record<string, ThemePresetDef> = {
  wireframe: {
    label: 'Wireframe',
    description: 'Sketch-style wireframe',
    configOverrides: {
      look: 'handDrawn',
      fontFamily: '"Caveat", cursive',
      fontSize: 18,
      flowchart: { curve: 'linear', nodeSpacing: 60, rankSpacing: 60, padding: 20 },
      sequence: { actorMargin: 60, messageMargin: 40 },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#f5f5f5',
        primaryTextColor: '#333333',
        primaryBorderColor: '#888888',
        secondaryColor: '#eeeeee',
        secondaryTextColor: '#555555',
        secondaryBorderColor: '#aaaaaa',
        tertiaryColor: '#fafafa',
        tertiaryTextColor: '#666666',
        tertiaryBorderColor: '#cccccc',
        lineColor: '#777777',
        titleColor: '#333333',
        fontFamily: '"Caveat", cursive',
      },
      flowchart: {
        mainBkg: '#f5f5f5',
        nodeBorder: '#888888',
        nodeTextColor: '#333333',
        clusterBkg: '#fafafa',
        clusterBorder: '#cccccc',
        edgeLabelBackground: '#ffffff',
        defaultLinkColor: '#777777',
      },
      sequence: {
        actorBkg: '#f5f5f5',
        actorBorder: '#888888',
        actorTextColor: '#333333',
        actorLineColor: '#888888',
        signalColor: '#777777',
        signalTextColor: '#333333',
        labelBoxBkgColor: '#f5f5f5',
        labelBoxBorderColor: '#aaaaaa',
        labelTextColor: '#333333',
        loopTextColor: '#666666',
        activationBkgColor: '#eeeeee',
        activationBorderColor: '#999999',
        sequenceNumberColor: '#333333',
        noteBkgColor: '#fff9c4',
        noteTextColor: '#333333',
        noteBorderColor: '#e6d85e',
      },
      er: {
        attributeBackgroundColorOdd: '#ffffff',
        attributeBackgroundColorEven: '#f5f5f5',
      },
      state: {
        stateBkg: '#f5f5f5',
        stateLabelColor: '#333333',
        compositeBackground: '#fafafa',
        compositeTitleBackground: '#eeeeee',
        compositeBorder: '#aaaaaa',
        transitionColor: '#777777',
        transitionLabelColor: '#555555',
        specialStateColor: '#888888',
        errorBkgColor: '#ffdddd',
        errorTextColor: '#333333',
      },
      class: {
        classText: '#333333',
        fillType0: '#f5f5f5',
        fillType1: '#eeeeee',
        fillType2: '#e8e8e8',
        fillType3: '#dddddd',
        fillType4: '#d5d5d5',
        fillType5: '#cccccc',
        fillType6: '#c0c0c0',
        fillType7: '#b8b8b8',
      },
      gantt: {
        sectionBkgColor: '#f5f5f5',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#888888',
        taskBkgColor: '#eeeeee',
        taskTextColor: '#333333',
        taskTextLightColor: '#333333',
        taskTextDarkColor: '#333333',
        taskTextOutsideColor: '#333333',
        activeTaskBorderColor: '#666666',
        activeTaskBkgColor: '#dddddd',
        doneTaskBkgColor: '#cccccc',
        doneTaskBorderColor: '#999999',
        critBkgColor: '#ffdddd',
        critBorderColor: '#cc0000',
        todayLineColor: '#cc0000',
      },
      git: {
        git0: '#888888',
        git1: '#aaaaaa',
        git2: '#666666',
        git3: '#999999',
        git4: '#777777',
        git5: '#bbbbbb',
        git6: '#555555',
        git7: '#888888',
        gitBranchLabel0: '#000000',
        gitBranchLabel1: '#333333',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#333333',
        gitBranchLabel4: '#000000',
        gitBranchLabel5: '#333333',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#000000',
      },
      pie: {
        pie1: '#f5f5f5',
        pie2: '#dddddd',
        pie3: '#cccccc',
        pie4: '#bbbbbb',
        pie5: '#aaaaaa',
        pie6: '#999999',
        pie7: '#888888',
        pie8: '#777777',
        pieTitleTextColor: '#333333',
        pieSectionTextColor: '#333333',
        pieStrokeColor: '#888888',
      },
      requirement: {
        requirementBackground: '#f5f5f5',
        requirementBorderColor: '#888888',
        requirementTextColor: '#333333',
        relationColor: '#777777',
        relationLabelBackground: '#ffffff',
        relationLabelColor: '#555555',
      },
      quadrant: {
        quadrant1Fill: '#f5f5f5',
        quadrant2Fill: '#eeeeee',
        quadrant3Fill: '#e8e8e8',
        quadrant4Fill: '#f0f0f0',
        quadrant1TextFill: '#333333',
        quadrant2TextFill: '#333333',
        quadrant3TextFill: '#333333',
        quadrant4TextFill: '#333333',
        quadrantPointFill: '#888888',
        quadrantPointTextFill: '#000000',
        quadrantXAxisTextFill: '#555555',
        quadrantYAxisTextFill: '#555555',
        quadrantTitleFill: '#333333',
      },
      architecture: {
        archEdgeColor: '#777777',
        archEdgeArrowColor: '#777777',
        archGroupBorderColor: '#888888',
      },
      journey: {
        cScale0: '#f5f5f5',
        cScale1: '#eeeeee',
        cScale2: '#e0e0e0',
        cScale3: '#d5d5d5',
        cScale4: '#cccccc',
        cScale5: '#bbbbbb',
        cScale6: '#aaaaaa',
        cScale7: '#999999',
        cScale8: '#888888',
        cScale9: '#777777',
        cScale10: '#666666',
        cScale11: '#555555',
      },
    },
  },

  corporate: {
    label: 'Corporate',
    description: 'Clean business pastels',
    configOverrides: {
      look: 'classic',
      fontFamily: '"Source Sans 3", "Segoe UI", sans-serif',
      fontSize: 15,
      flowchart: { curve: 'monotoneX', nodeSpacing: 55, rankSpacing: 55, padding: 18 },
      sequence: { actorMargin: 55, messageMargin: 38, width: 160 },
      gantt: { barHeight: 24, barGap: 6 },
      xyChart: { plotColorPalette: '#3b82f6,#0ea5e9,#06b6d4,#6366f1,#8b5cf6,#64748b' },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#dbeafe',
        primaryTextColor: '#1e293b',
        primaryBorderColor: '#93c5fd',
        secondaryColor: '#ccfbf1',
        secondaryTextColor: '#1e293b',
        secondaryBorderColor: '#5eead4',
        tertiaryColor: '#e0f2fe',
        tertiaryTextColor: '#1e293b',
        tertiaryBorderColor: '#7dd3fc',
        lineColor: '#94a3b8',
        titleColor: '#0f172a',
        fontFamily: '"Source Sans 3", "Segoe UI", sans-serif',
      },
      flowchart: {
        mainBkg: '#dbeafe',
        nodeBorder: '#93c5fd',
        nodeTextColor: '#1e293b',
        clusterBkg: '#f8fafc',
        clusterBorder: '#cbd5e1',
        edgeLabelBackground: '#ffffff',
        defaultLinkColor: '#94a3b8',
      },
      sequence: {
        actorBkg: '#dbeafe',
        actorBorder: '#93c5fd',
        actorTextColor: '#1e293b',
        actorLineColor: '#93c5fd',
        signalColor: '#64748b',
        signalTextColor: '#1e293b',
        labelBoxBkgColor: '#ccfbf1',
        labelBoxBorderColor: '#5eead4',
        labelTextColor: '#1e293b',
        loopTextColor: '#475569',
        activationBkgColor: '#bfdbfe',
        activationBorderColor: '#60a5fa',
        sequenceNumberColor: '#1e293b',
        noteBkgColor: '#fef9c3',
        noteTextColor: '#1e293b',
        noteBorderColor: '#fde047',
      },
      er: {
        attributeBackgroundColorOdd: '#ffffff',
        attributeBackgroundColorEven: '#f0f7ff',
      },
      state: {
        stateBkg: '#dbeafe',
        stateLabelColor: '#1e293b',
        compositeBackground: '#f8fafc',
        compositeTitleBackground: '#e0f2fe',
        compositeBorder: '#93c5fd',
        transitionColor: '#94a3b8',
        transitionLabelColor: '#475569',
        specialStateColor: '#3b82f6',
        errorBkgColor: '#fee2e2',
        errorTextColor: '#991b1b',
      },
      class: {
        classText: '#1e293b',
        fillType0: '#dbeafe',
        fillType1: '#ccfbf1',
        fillType2: '#e0f2fe',
        fillType3: '#bfdbfe',
        fillType4: '#a5f3fc',
        fillType5: '#bae6fd',
        fillType6: '#dbeafe',
        fillType7: '#ccfbf1',
      },
      gantt: {
        sectionBkgColor: '#eff6ff',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#93c5fd',
        taskBkgColor: '#dbeafe',
        taskTextColor: '#1e293b',
        taskTextLightColor: '#1e293b',
        taskTextDarkColor: '#1e293b',
        taskTextOutsideColor: '#1e293b',
        activeTaskBorderColor: '#3b82f6',
        activeTaskBkgColor: '#bfdbfe',
        doneTaskBkgColor: '#94a3b8',
        doneTaskBorderColor: '#64748b',
        critBkgColor: '#fee2e2',
        critBorderColor: '#ef4444',
        todayLineColor: '#3b82f6',
      },
      git: {
        git0: '#3b82f6',
        git1: '#0ea5e9',
        git2: '#06b6d4',
        git3: '#6366f1',
        git4: '#8b5cf6',
        git5: '#64748b',
        git6: '#0284c7',
        git7: '#0369a1',
        gitBranchLabel0: '#000000',
        gitBranchLabel1: '#000000',
        gitBranchLabel2: '#000000',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#000000',
        gitBranchLabel5: '#ffffff',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#3b82f6',
        pie2: '#0ea5e9',
        pie3: '#06b6d4',
        pie4: '#6366f1',
        pie5: '#8b5cf6',
        pie6: '#64748b',
        pie7: '#0284c7',
        pie8: '#0369a1',
        pieTitleTextColor: '#0f172a',
        pieSectionTextColor: '#000000',
        pieStrokeColor: '#ffffff',
      },
      requirement: {
        requirementBackground: '#dbeafe',
        requirementBorderColor: '#93c5fd',
        requirementTextColor: '#1e293b',
        relationColor: '#94a3b8',
        relationLabelBackground: '#ffffff',
        relationLabelColor: '#475569',
      },
      quadrant: {
        quadrant1Fill: '#dbeafe',
        quadrant2Fill: '#e0f2fe',
        quadrant3Fill: '#ccfbf1',
        quadrant4Fill: '#eff6ff',
        quadrant1TextFill: '#1e293b',
        quadrant2TextFill: '#1e293b',
        quadrant3TextFill: '#1e293b',
        quadrant4TextFill: '#1e293b',
        quadrantPointFill: '#3b82f6',
        quadrantPointTextFill: '#000000',
        quadrantXAxisTextFill: '#475569',
        quadrantYAxisTextFill: '#475569',
        quadrantTitleFill: '#0f172a',
      },
      architecture: {
        archEdgeColor: '#94a3b8',
        archEdgeArrowColor: '#94a3b8',
        archGroupBorderColor: '#93c5fd',
      },
      journey: {
        cScale0: '#dbeafe',
        cScale1: '#bfdbfe',
        cScale2: '#93c5fd',
        cScale3: '#60a5fa',
        cScale4: '#3b82f6',
        cScale5: '#2563eb',
        cScale6: '#1d4ed8',
        cScale7: '#0ea5e9',
        cScale8: '#06b6d4',
        cScale9: '#6366f1',
        cScale10: '#8b5cf6',
        cScale11: '#64748b',
      },
    },
  },
  amethyst: {
    label: 'Amethyst',
    description: 'Rich purple palette',
    configOverrides: {
      look: 'classic',
      fontFamily: '"Poppins", sans-serif',
      fontSize: 14,
      flowchart: { curve: 'cardinal', nodeSpacing: 44, rankSpacing: 50, padding: 14 },
      sequence: { actorMargin: 45, messageMargin: 30, width: 140 },
      xyChart: { plotColorPalette: '#7c3aed,#a78bfa,#6d28d9,#c4b5fd,#5b21b6,#ddd6fe' },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#ede9fe',
        primaryTextColor: '#3b0764',
        primaryBorderColor: '#7c3aed',
        secondaryColor: '#7c3aed',
        secondaryTextColor: '#ffffff',
        secondaryBorderColor: '#6d28d9',
        tertiaryColor: '#ddd6fe',
        tertiaryTextColor: '#3b0764',
        tertiaryBorderColor: '#a78bfa',
        lineColor: '#7c3aed',
        titleColor: '#4c1d95',
        fontFamily: '"Poppins", sans-serif',
      },
      flowchart: {
        mainBkg: '#ede9fe',
        nodeBorder: '#7c3aed',
        nodeTextColor: '#3b0764',
        clusterBkg: '#f5f3ff',
        clusterBorder: '#a78bfa',
        edgeLabelBackground: '#faf5ff',
        defaultLinkColor: '#7c3aed',
      },
      sequence: {
        actorBkg: '#7c3aed',
        actorBorder: '#6d28d9',
        actorTextColor: '#ffffff',
        actorLineColor: '#6d28d9',
        signalColor: '#6d28d9',
        signalTextColor: '#4c1d95',
        labelBoxBkgColor: '#ede9fe',
        labelBoxBorderColor: '#a78bfa',
        labelTextColor: '#3b0764',
        loopTextColor: '#6d28d9',
        activationBkgColor: '#c4b5fd',
        activationBorderColor: '#7c3aed',
        sequenceNumberColor: '#3b0764',
        noteBkgColor: '#f5f3ff',
        noteTextColor: '#4c1d95',
        noteBorderColor: '#c4b5fd',
      },
      er: {
        attributeBackgroundColorOdd: '#f5f3ff',
        attributeBackgroundColorEven: '#ede9fe',
      },
      state: {
        stateBkg: '#ede9fe',
        stateLabelColor: '#3b0764',
        compositeBackground: '#f5f3ff',
        compositeTitleBackground: '#ddd6fe',
        compositeBorder: '#a78bfa',
        transitionColor: '#7c3aed',
        transitionLabelColor: '#4c1d95',
        specialStateColor: '#6d28d9',
        errorBkgColor: '#fee2e2',
        errorTextColor: '#991b1b',
      },
      class: {
        classText: '#3b0764',
        fillType0: '#ede9fe',
        fillType1: '#ddd6fe',
        fillType2: '#c4b5fd',
        fillType3: '#a78bfa',
        fillType4: '#8b5cf6',
        fillType5: '#7c3aed',
        fillType6: '#6d28d9',
        fillType7: '#5b21b6',
      },
      gantt: {
        sectionBkgColor: '#f5f3ff',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#7c3aed',
        taskBkgColor: '#ede9fe',
        taskTextColor: '#3b0764',
        taskTextLightColor: '#3b0764',
        taskTextDarkColor: '#3b0764',
        taskTextOutsideColor: '#3b0764',
        activeTaskBorderColor: '#6d28d9',
        activeTaskBkgColor: '#ddd6fe',
        doneTaskBkgColor: '#a78bfa',
        doneTaskBorderColor: '#7c3aed',
        critBkgColor: '#fee2e2',
        critBorderColor: '#ef4444',
        todayLineColor: '#6d28d9',
      },
      git: {
        git0: '#7c3aed',
        git1: '#6d28d9',
        git2: '#a78bfa',
        git3: '#8b5cf6',
        git4: '#4c1d95',
        git5: '#c4b5fd',
        git6: '#5b21b6',
        git7: '#7c3aed',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#3b0764',
        gitBranchLabel3: '#000000',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#3b0764',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#7c3aed',
        pie2: '#8b5cf6',
        pie3: '#6d28d9',
        pie4: '#7c3aed',
        pie5: '#5b21b6',
        pie6: '#ddd6fe',
        pie7: '#8b5cf6',
        pie8: '#4c1d95',
        pieTitleTextColor: '#4c1d95',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#ffffff',
      },
      requirement: {
        requirementBackground: '#ede9fe',
        requirementBorderColor: '#7c3aed',
        requirementTextColor: '#3b0764',
        relationColor: '#7c3aed',
        relationLabelBackground: '#f5f3ff',
        relationLabelColor: '#4c1d95',
      },
      quadrant: {
        quadrant1Fill: '#ede9fe',
        quadrant2Fill: '#ddd6fe',
        quadrant3Fill: '#f5f3ff',
        quadrant4Fill: '#faf5ff',
        quadrant1TextFill: '#3b0764',
        quadrant2TextFill: '#3b0764',
        quadrant3TextFill: '#3b0764',
        quadrant4TextFill: '#3b0764',
        quadrantPointFill: '#7c3aed',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#4c1d95',
        quadrantYAxisTextFill: '#4c1d95',
        quadrantTitleFill: '#4c1d95',
      },
      architecture: {
        archEdgeColor: '#7c3aed',
        archEdgeArrowColor: '#7c3aed',
        archGroupBorderColor: '#a78bfa',
      },
      journey: {
        cScale0: '#ede9fe',
        cScale1: '#ddd6fe',
        cScale2: '#c4b5fd',
        cScale3: '#a78bfa',
        cScale4: '#8b5cf6',
        cScale5: '#7c3aed',
        cScale6: '#6d28d9',
        cScale7: '#5b21b6',
        cScale8: '#4c1d95',
        cScale9: '#3b0764',
        cScale10: '#f5f3ff',
        cScale11: '#faf5ff',
      },
    },
  },

  neon: {
    label: 'Neon',
    description: 'Electric brutalist colors',
    configOverrides: {
      look: 'classic',
      fontFamily: '"Space Mono", monospace',
      fontSize: 13,
      flowchart: { curve: 'step', nodeSpacing: 45, rankSpacing: 50, padding: 10 },
      sequence: { showSequenceNumbers: true, actorMargin: 40, messageMargin: 30, width: 130 },
      gantt: { barHeight: 28, barGap: 2 },
      xyChart: { plotColorPalette: '#2d2dff,#ff2d9b,#00cc44,#ff8800,#00cccc,#cc00ff,#ffcc00' },
    },
    vars: {
      core: {
        background: '#ffffff',
        primaryColor: '#2d2dff',
        primaryTextColor: '#ffffff',
        primaryBorderColor: '#000000',
        secondaryColor: '#ff2d9b',
        secondaryTextColor: '#000000',
        secondaryBorderColor: '#000000',
        tertiaryColor: '#e8ff00',
        tertiaryTextColor: '#000000',
        tertiaryBorderColor: '#000000',
        lineColor: '#111111',
        titleColor: '#000000',
        fontFamily: '"Space Mono", monospace',
      },
      flowchart: {
        mainBkg: '#2d2dff',
        nodeBorder: '#000000',
        nodeTextColor: '#ffffff',
        clusterBkg: '#e8ff00',
        clusterBorder: '#000000',
        edgeLabelBackground: '#2d2dff',
        defaultLinkColor: '#111111',
      },
      sequence: {
        actorBkg: '#2d2dff',
        actorBorder: '#000000',
        actorTextColor: '#ffffff',
        actorLineColor: '#000000',
        signalColor: '#000000',
        signalTextColor: '#000000',
        labelBoxBkgColor: '#ff2d9b',
        labelBoxBorderColor: '#000000',
        labelTextColor: '#000000',
        loopTextColor: '#000000',
        activationBkgColor: '#e8ff00',
        activationBorderColor: '#000000',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#e8ff00',
        noteTextColor: '#000000',
        noteBorderColor: '#000000',
      },
      er: {
        attributeBackgroundColorOdd: '#3333dd',
        attributeBackgroundColorEven: '#1a1acc',
      },
      state: {
        stateBkg: '#2d2dff',
        stateLabelColor: '#ffffff',
        compositeBackground: '#f0f0ff',
        compositeTitleBackground: '#1a1acc',
        compositeBorder: '#000000',
        transitionColor: '#111111',
        transitionLabelColor: '#000000',
        specialStateColor: '#ff2d9b',
        errorBkgColor: '#ff2d9b',
        errorTextColor: '#000000',
      },
      class: {
        classText: '#ffffff',
        fillType0: '#2d2dff',
        fillType1: '#cc0066',
        fillType2: '#806600',
        fillType3: '#008833',
        fillType4: '#ff8800',
        fillType5: '#00cccc',
        fillType6: '#cc00ff',
        fillType7: '#ffcc00',
      },
      gantt: {
        sectionBkgColor: '#e8e8ff',
        altSectionBkgColor: '#ffffff',
        taskBorderColor: '#000000',
        taskBkgColor: '#2d2dff',
        taskTextColor: '#ffffff',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#000000',
        taskTextOutsideColor: '#000000',
        activeTaskBorderColor: '#000000',
        activeTaskBkgColor: '#ff2d9b',
        doneTaskBkgColor: '#00cc44',
        doneTaskBorderColor: '#000000',
        critBkgColor: '#cc0000',
        critBorderColor: '#000000',
        todayLineColor: '#ff2d9b',
      },
      git: {
        git0: '#2d2dff',
        git1: '#ff2d9b',
        git2: '#00cc44',
        git3: '#ff8800',
        git4: '#00cccc',
        git5: '#cc00ff',
        git6: '#ffcc00',
        git7: '#2d2dff',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#000000',
        gitBranchLabel3: '#000000',
        gitBranchLabel4: '#000000',
        gitBranchLabel5: '#000000',
        gitBranchLabel6: '#000000',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#2d2dff',
        pie2: '#cc0066',
        pie3: '#806600',
        pie4: '#008833',
        pie5: '#cc5500',
        pie6: '#008888',
        pie7: '#9900cc',
        pie8: '#cc9900',
        pieTitleTextColor: '#000000',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#000000',
      },
      requirement: {
        requirementBackground: '#e8e8ff',
        requirementBorderColor: '#000000',
        requirementTextColor: '#000000',
        relationColor: '#111111',
        relationLabelBackground: '#e8ff00',
        relationLabelColor: '#000000',
      },
      quadrant: {
        quadrant1Fill: '#2d2dff',
        quadrant2Fill: '#ff2d9b',
        quadrant3Fill: '#e8ff00',
        quadrant4Fill: '#00cccc',
        quadrant1TextFill: '#ffffff',
        quadrant2TextFill: '#000000',
        quadrant3TextFill: '#000000',
        quadrant4TextFill: '#000000',
        quadrantPointFill: '#ff8800',
        quadrantPointTextFill: '#000000',
        quadrantXAxisTextFill: '#000000',
        quadrantYAxisTextFill: '#000000',
        quadrantTitleFill: '#000000',
      },
      architecture: {
        archEdgeColor: '#111111',
        archEdgeArrowColor: '#111111',
        archGroupBorderColor: '#000000',
      },
      journey: {
        cScale0: '#2d2dff',
        cScale1: '#ff2d9b',
        cScale2: '#e8ff00',
        cScale3: '#00cc44',
        cScale4: '#ff8800',
        cScale5: '#00cccc',
        cScale6: '#cc00ff',
        cScale7: '#ffcc00',
        cScale8: '#2d2dff',
        cScale9: '#ff2d9b',
        cScale10: '#e8ff00',
        cScale11: '#00cc44',
      },
    },
  },

  newsprint: {
    label: 'Newsprint',
    description: 'Editorial serif palette inspired by quality broadsheets',
    configOverrides: {
      look: 'classic' as const,
      fontFamily: '"Playfair Display", "Georgia", serif',
      fontSize: 15,
      flowchart: { curve: 'monotoneX' as const, nodeSpacing: 55, rankSpacing: 58, padding: 18, diagramPadding: 12 },
      sequence: { showSequenceNumbers: false, mirrorActors: false, actorMargin: 55, messageMargin: 36, width: 155 },
      gantt: { barHeight: 22, barGap: 5, topPadding: 50, axisFormat: '%b %d' },
      xyChart: { plotColorPalette: '#c41d1d,#1a1a1a,#6b6b6b,#7a6a52,#2e5d4b,#6b3a1a' },
    },
    vars: {
      core: {
        background: '#faf8f4',
        primaryColor: '#f0ece4',
        primaryTextColor: '#1a1a1a',
        primaryBorderColor: '#1a1a1a',
        secondaryColor: '#e8e2d6',
        secondaryTextColor: '#1a1a1a',
        secondaryBorderColor: '#8a8278',
        tertiaryColor: '#f5f1ea',
        tertiaryTextColor: '#333333',
        tertiaryBorderColor: '#b0a898',
        lineColor: '#4a4540',
        titleColor: '#1a1a1a',
        fontFamily: '"Playfair Display", "Georgia", serif',
      },
      flowchart: {
        mainBkg: '#f0ece4',
        nodeBorder: '#1a1a1a',
        nodeTextColor: '#1a1a1a',
        clusterBkg: '#f5f1ea',
        clusterBorder: '#8a8278',
        edgeLabelBackground: '#faf8f4',
        defaultLinkColor: '#4a4540',
      },
      sequence: {
        actorBkg: '#1a1a1a',
        actorBorder: '#1a1a1a',
        actorTextColor: '#faf8f4',
        actorLineColor: '#4a4540',
        signalColor: '#4a4540',
        signalTextColor: '#1a1a1a',
        labelBoxBkgColor: '#f0ece4',
        labelBoxBorderColor: '#8a8278',
        labelTextColor: '#1a1a1a',
        loopTextColor: '#4a4540',
        activationBkgColor: '#e8e2d6',
        activationBorderColor: '#1a1a1a',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#f5f1ea',
        noteTextColor: '#1a1a1a',
        noteBorderColor: '#b0a898',
      },
      er: {
        attributeBackgroundColorOdd: '#faf8f4',
        attributeBackgroundColorEven: '#f0ece4',
      },
      state: {
        stateBkg: '#f0ece4',
        stateLabelColor: '#1a1a1a',
        compositeBackground: '#f5f1ea',
        compositeTitleBackground: '#e8e2d6',
        compositeBorder: '#1a1a1a',
        transitionColor: '#4a4540',
        transitionLabelColor: '#1a1a1a',
        specialStateColor: '#4a4540',
        errorBkgColor: '#f5d5d5',
        errorTextColor: '#8b1a1a',
      },
      class: {
        classText: '#1a1a1a',
        fillType0: '#f0ece4',
        fillType1: '#e8e2d6',
        fillType2: '#ddd6c8',
        fillType3: '#d2ccbe',
        fillType4: '#c7c0b2',
        fillType5: '#bcb5a6',
        fillType6: '#b0a898',
        fillType7: '#a49c8c',
      },
      gantt: {
        sectionBkgColor: '#f5f1ea',
        altSectionBkgColor: '#faf8f4',
        taskBorderColor: '#1a1a1a',
        taskBkgColor: '#e8e2d6',
        taskTextColor: '#1a1a1a',
        taskTextLightColor: '#1a1a1a',
        taskTextDarkColor: '#1a1a1a',
        taskTextOutsideColor: '#1a1a1a',
        activeTaskBorderColor: '#c41d1d',
        activeTaskBkgColor: '#f0ece4',
        doneTaskBkgColor: '#b0a898',
        doneTaskBorderColor: '#8a8278',
        critBkgColor: '#f5d5d5',
        critBorderColor: '#c41d1d',
        todayLineColor: '#c41d1d',
      },
      git: {
        git0: '#1a1a1a',
        git1: '#c41d1d',
        git2: '#4a4540',
        git3: '#8a8278',
        git4: '#2e5d4b',
        git5: '#6b3a1a',
        git6: '#6b6b6b',
        git7: '#7a6a52',
        gitBranchLabel0: '#faf8f4',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#faf8f4',
        gitBranchLabel3: '#1a1a1a',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#ffffff',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#1a1a1a',
      },
      pie: {
        pie1: '#1a1a1a',
        pie2: '#c41d1d',
        pie3: '#6b6b6b',
        pie4: '#7a6a52',
        pie5: '#2e5d4b',
        pie6: '#6b3a1a',
        pie7: '#4a4540',
        pie8: '#8a8278',
        pieTitleTextColor: '#1a1a1a',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#faf8f4',
      },
      requirement: {
        requirementBackground: '#f0ece4',
        requirementBorderColor: '#1a1a1a',
        requirementTextColor: '#1a1a1a',
        relationColor: '#4a4540',
        relationLabelBackground: '#faf8f4',
        relationLabelColor: '#1a1a1a',
      },
      quadrant: {
        quadrant1Fill: '#f0ece4',
        quadrant2Fill: '#e8e2d6',
        quadrant3Fill: '#f5f1ea',
        quadrant4Fill: '#faf8f4',
        quadrant1TextFill: '#1a1a1a',
        quadrant2TextFill: '#1a1a1a',
        quadrant3TextFill: '#1a1a1a',
        quadrant4TextFill: '#1a1a1a',
        quadrantPointFill: '#c41d1d',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#4a4540',
        quadrantYAxisTextFill: '#4a4540',
        quadrantTitleFill: '#1a1a1a',
      },
      architecture: {
        archEdgeColor: '#4a4540',
        archEdgeArrowColor: '#4a4540',
        archGroupBorderColor: '#1a1a1a',
      },
      journey: {
        cScale0: '#f0ece4',
        cScale1: '#e8e2d6',
        cScale2: '#ddd6c8',
        cScale3: '#d2ccbe',
        cScale4: '#c7c0b2',
        cScale5: '#bcb5a6',
        cScale6: '#b0a898',
        cScale7: '#a49c8c',
        cScale8: '#988f80',
        cScale9: '#8a8278',
        cScale10: '#7c756c',
        cScale11: '#6e6860',
      },
    },
  },

  dataviz: {
    label: 'DataViz',
    description: 'Data journalism palette with bold analytical colors',
    configOverrides: {
      look: 'classic' as const,
      fontFamily: '"Inter", "Helvetica Neue", sans-serif',
      fontSize: 14,
      flowchart: { curve: 'basis' as const, nodeSpacing: 50, rankSpacing: 52, padding: 16, diagramPadding: 10 },
      sequence: { showSequenceNumbers: true, mirrorActors: false, actorMargin: 48, messageMargin: 32, width: 145 },
      gantt: { barHeight: 24, barGap: 4, topPadding: 48, axisFormat: '%b %d' },
      xyChart: { plotColorPalette: '#e6550d,#3182bd,#31a354,#756bb1,#636363,#de9ed6' },
    },
    vars: {
      core: {
        background: '#f0f0f0',
        primaryColor: '#3182bd',
        primaryTextColor: '#ffffff',
        primaryBorderColor: '#2171a5',
        secondaryColor: '#e6550d',
        secondaryTextColor: '#ffffff',
        secondaryBorderColor: '#c94508',
        tertiaryColor: '#eaeaea',
        tertiaryTextColor: '#222222',
        tertiaryBorderColor: '#aaaaaa',
        lineColor: '#636363',
        titleColor: '#222222',
        fontFamily: '"Inter", "Helvetica Neue", sans-serif',
      },
      flowchart: {
        mainBkg: '#3182bd',
        nodeBorder: '#2171a5',
        nodeTextColor: '#ffffff',
        clusterBkg: '#e8e8e8',
        clusterBorder: '#aaaaaa',
        edgeLabelBackground: '#f0f0f0',
        defaultLinkColor: '#636363',
      },
      sequence: {
        actorBkg: '#3182bd',
        actorBorder: '#2171a5',
        actorTextColor: '#ffffff',
        actorLineColor: '#636363',
        signalColor: '#636363',
        signalTextColor: '#222222',
        labelBoxBkgColor: '#e6550d',
        labelBoxBorderColor: '#c94508',
        labelTextColor: '#ffffff',
        loopTextColor: '#444444',
        activationBkgColor: '#d0e2f0',
        activationBorderColor: '#3182bd',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#fff7bc',
        noteTextColor: '#222222',
        noteBorderColor: '#e6ab02',
      },
      er: {
        attributeBackgroundColorOdd: '#f0f0f0',
        attributeBackgroundColorEven: '#e4e4e4',
      },
      state: {
        stateBkg: '#d0e2f0',
        stateLabelColor: '#222222',
        compositeBackground: '#e8e8e8',
        compositeTitleBackground: '#d0e2f0',
        compositeBorder: '#aaaaaa',
        transitionColor: '#636363',
        transitionLabelColor: '#222222',
        specialStateColor: '#e6550d',
        errorBkgColor: '#fee0d2',
        errorTextColor: '#a63603',
      },
      class: {
        classText: '#ffffff',
        fillType0: '#3182bd',
        fillType1: '#e6550d',
        fillType2: '#31a354',
        fillType3: '#756bb1',
        fillType4: '#636363',
        fillType5: '#de9ed6',
        fillType6: '#e6ab02',
        fillType7: '#a63603',
      },
      gantt: {
        sectionBkgColor: '#e8e8e8',
        altSectionBkgColor: '#f0f0f0',
        taskBorderColor: '#2171a5',
        taskBkgColor: '#3182bd',
        taskTextColor: '#ffffff',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#222222',
        taskTextOutsideColor: '#222222',
        activeTaskBorderColor: '#c94508',
        activeTaskBkgColor: '#e6550d',
        doneTaskBkgColor: '#969696',
        doneTaskBorderColor: '#636363',
        critBkgColor: '#fee0d2',
        critBorderColor: '#e6550d',
        todayLineColor: '#e6550d',
      },
      git: {
        git0: '#3182bd',
        git1: '#e6550d',
        git2: '#31a354',
        git3: '#756bb1',
        git4: '#636363',
        git5: '#de9ed6',
        git6: '#e6ab02',
        git7: '#a63603',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#222222',
        gitBranchLabel6: '#222222',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#3182bd',
        pie2: '#e6550d',
        pie3: '#31a354',
        pie4: '#756bb1',
        pie5: '#636363',
        pie6: '#de9ed6',
        pie7: '#e6ab02',
        pie8: '#a63603',
        pieTitleTextColor: '#222222',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#f0f0f0',
      },
      requirement: {
        requirementBackground: '#d0e2f0',
        requirementBorderColor: '#2171a5',
        requirementTextColor: '#222222',
        relationColor: '#636363',
        relationLabelBackground: '#f0f0f0',
        relationLabelColor: '#222222',
      },
      quadrant: {
        quadrant1Fill: '#d0e2f0',
        quadrant2Fill: '#fee0d2',
        quadrant3Fill: '#e8e8e8',
        quadrant4Fill: '#d5e8d4',
        quadrant1TextFill: '#222222',
        quadrant2TextFill: '#222222',
        quadrant3TextFill: '#222222',
        quadrant4TextFill: '#222222',
        quadrantPointFill: '#e6550d',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#444444',
        quadrantYAxisTextFill: '#444444',
        quadrantTitleFill: '#222222',
      },
      architecture: {
        archEdgeColor: '#636363',
        archEdgeArrowColor: '#636363',
        archGroupBorderColor: '#2171a5',
      },
      journey: {
        cScale0: '#d0e2f0',
        cScale1: '#3182bd',
        cScale2: '#e6550d',
        cScale3: '#31a354',
        cScale4: '#756bb1',
        cScale5: '#636363',
        cScale6: '#de9ed6',
        cScale7: '#e6ab02',
        cScale8: '#a63603',
        cScale9: '#fdae6b',
        cScale10: '#6baed6',
        cScale11: '#74c476',
      },
    },
  },

  evergreen: {
    label: 'Evergreen',
    description: 'Utilitarian wire-service clarity with warm accents',
    configOverrides: {
      look: 'classic' as const,
      fontFamily: '"Roboto Condensed", "Arial Narrow", sans-serif',
      fontSize: 13,
      flowchart: { curve: 'linear' as const, nodeSpacing: 42, rankSpacing: 46, padding: 12, diagramPadding: 8 },
      sequence: { showSequenceNumbers: true, mirrorActors: true, actorMargin: 42, messageMargin: 28, width: 130 },
      gantt: { barHeight: 20, barGap: 3, topPadding: 44, axisFormat: '%m/%d' },
      xyChart: { plotColorPalette: '#d45b07,#1b7a4e,#2b6ca3,#7a5195,#6a6a6a,#c4962c' },
    },
    vars: {
      core: {
        background: '#f7f7f5',
        primaryColor: '#1b7a4e',
        primaryTextColor: '#ffffff',
        primaryBorderColor: '#146340',
        secondaryColor: '#d45b07',
        secondaryTextColor: '#ffffff',
        secondaryBorderColor: '#b04a06',
        tertiaryColor: '#eeeee8',
        tertiaryTextColor: '#2d2d2d',
        tertiaryBorderColor: '#999999',
        lineColor: '#555555',
        titleColor: '#1a1a1a',
        fontFamily: '"Roboto Condensed", "Arial Narrow", sans-serif',
      },
      flowchart: {
        mainBkg: '#1b7a4e',
        nodeBorder: '#146340',
        nodeTextColor: '#ffffff',
        clusterBkg: '#eeeee8',
        clusterBorder: '#999999',
        edgeLabelBackground: '#f7f7f5',
        defaultLinkColor: '#555555',
      },
      sequence: {
        actorBkg: '#1b7a4e',
        actorBorder: '#146340',
        actorTextColor: '#ffffff',
        actorLineColor: '#555555',
        signalColor: '#555555',
        signalTextColor: '#2d2d2d',
        labelBoxBkgColor: '#d45b07',
        labelBoxBorderColor: '#b04a06',
        labelTextColor: '#ffffff',
        loopTextColor: '#555555',
        activationBkgColor: '#cce5d8',
        activationBorderColor: '#1b7a4e',
        sequenceNumberColor: '#ffffff',
        noteBkgColor: '#fef4e8',
        noteTextColor: '#2d2d2d',
        noteBorderColor: '#c4962c',
      },
      er: {
        attributeBackgroundColorOdd: '#f7f7f5',
        attributeBackgroundColorEven: '#eeeee8',
      },
      state: {
        stateBkg: '#cce5d8',
        stateLabelColor: '#2d2d2d',
        compositeBackground: '#eeeee8',
        compositeTitleBackground: '#cce5d8',
        compositeBorder: '#999999',
        transitionColor: '#555555',
        transitionLabelColor: '#2d2d2d',
        specialStateColor: '#d45b07',
        errorBkgColor: '#fde0d0',
        errorTextColor: '#8b2500',
      },
      class: {
        classText: '#ffffff',
        fillType0: '#1b7a4e',
        fillType1: '#d45b07',
        fillType2: '#2b6ca3',
        fillType3: '#7a5195',
        fillType4: '#6a6a6a',
        fillType5: '#c4962c',
        fillType6: '#146340',
        fillType7: '#b04a06',
      },
      gantt: {
        sectionBkgColor: '#eeeee8',
        altSectionBkgColor: '#f7f7f5',
        taskBorderColor: '#146340',
        taskBkgColor: '#1b7a4e',
        taskTextColor: '#ffffff',
        taskTextLightColor: '#ffffff',
        taskTextDarkColor: '#2d2d2d',
        taskTextOutsideColor: '#2d2d2d',
        activeTaskBorderColor: '#b04a06',
        activeTaskBkgColor: '#d45b07',
        doneTaskBkgColor: '#999999',
        doneTaskBorderColor: '#6a6a6a',
        critBkgColor: '#fde0d0',
        critBorderColor: '#d45b07',
        todayLineColor: '#d45b07',
      },
      git: {
        git0: '#1b7a4e',
        git1: '#d45b07',
        git2: '#2b6ca3',
        git3: '#7a5195',
        git4: '#6a6a6a',
        git5: '#c4962c',
        git6: '#146340',
        git7: '#b04a06',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#ffffff',
        gitBranchLabel5: '#222222',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#1b7a4e',
        pie2: '#d45b07',
        pie3: '#2b6ca3',
        pie4: '#7a5195',
        pie5: '#6a6a6a',
        pie6: '#c4962c',
        pie7: '#146340',
        pie8: '#b04a06',
        pieTitleTextColor: '#1a1a1a',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#f7f7f5',
      },
      requirement: {
        requirementBackground: '#cce5d8',
        requirementBorderColor: '#146340',
        requirementTextColor: '#2d2d2d',
        relationColor: '#555555',
        relationLabelBackground: '#f7f7f5',
        relationLabelColor: '#2d2d2d',
      },
      quadrant: {
        quadrant1Fill: '#cce5d8',
        quadrant2Fill: '#fde0d0',
        quadrant3Fill: '#eeeee8',
        quadrant4Fill: '#d4e4f0',
        quadrant1TextFill: '#2d2d2d',
        quadrant2TextFill: '#2d2d2d',
        quadrant3TextFill: '#2d2d2d',
        quadrant4TextFill: '#2d2d2d',
        quadrantPointFill: '#d45b07',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#555555',
        quadrantYAxisTextFill: '#555555',
        quadrantTitleFill: '#1a1a1a',
      },
      architecture: {
        archEdgeColor: '#555555',
        archEdgeArrowColor: '#555555',
        archGroupBorderColor: '#146340',
      },
      journey: {
        cScale0: '#cce5d8',
        cScale1: '#1b7a4e',
        cScale2: '#d45b07',
        cScale3: '#2b6ca3',
        cScale4: '#7a5195',
        cScale5: '#6a6a6a',
        cScale6: '#c4962c',
        cScale7: '#146340',
        cScale8: '#b04a06',
        cScale9: '#f0d5a0',
        cScale10: '#a0c8b8',
        cScale11: '#a0c0e0',
      },
    },
  },

  blueprint: {
    label: 'Blueprint',
    description: 'Technical blueprint with deep navy borders and monospace font',
    configOverrides: {
      look: 'classic' as const,
      fontFamily: '"JetBrains Mono", monospace',
      fontSize: 13,
      flowchart: { curve: 'linear' as const, nodeSpacing: 48, rankSpacing: 52, padding: 16, diagramPadding: 10 },
      sequence: { showSequenceNumbers: false, mirrorActors: false, messageMargin: 30, actorMargin: 50, width: 140 },
      gantt: { barHeight: 18, barGap: 4, topPadding: 48, axisFormat: '%Y-%m-%d' },
    },
    vars: {
      core: {
        background: '#f5f8ff',
        primaryColor: '#e8eef8',
        primaryTextColor: '#0a2d6b',
        primaryBorderColor: '#0a2d6b',
        secondaryColor: '#e8f0ff',
        secondaryTextColor: '#1a3a8a',
        secondaryBorderColor: '#1a3a8a',
        tertiaryColor: '#edf1fb',
        tertiaryTextColor: '#2a4a7a',
        tertiaryBorderColor: '#2a4a7a',
        lineColor: '#1a4a9a',
        titleColor: '#0a2d6b',
        fontFamily: '"JetBrains Mono", monospace',
      },
      flowchart: {
        mainBkg: '#e8eef8',
        nodeBorder: '#0a2d6b',
        nodeTextColor: '#0a2d6b',
        clusterBkg: '#eef2fc',
        clusterBorder: '#1a4a9a',
        edgeLabelBackground: '#f0f4ff',
        defaultLinkColor: '#1a4a9a',
      },
      sequence: {
        actorBkg: '#e8eef8',
        actorBorder: '#0a2d6b',
        actorTextColor: '#0a2d6b',
        actorLineColor: '#0a2d6b',
        signalColor: '#0a2d6b',
        signalTextColor: '#0a2d6b',
        labelBoxBkgColor: '#e8eef8',
        labelBoxBorderColor: '#0a2d6b',
        labelTextColor: '#0a2d6b',
        loopTextColor: '#0a2d6b',
        activationBkgColor: '#c8d8f0',
        activationBorderColor: '#0a2d6b',
        sequenceNumberColor: '#0a2d6b',
        noteBkgColor: '#eef3ff',
        noteTextColor: '#0a2d6b',
        noteBorderColor: '#1a4a9a',
      },
      er: {
        attributeBackgroundColorOdd: '#f5f8ff',
        attributeBackgroundColorEven: '#e8eef8',
      },
      state: {
        stateBkg: '#e8eef8',
        stateLabelColor: '#0a2d6b',
        compositeBackground: '#eef2fc',
        compositeTitleBackground: '#d8e4f4',
        compositeBorder: '#0a2d6b',
        transitionColor: '#1a4a9a',
        transitionLabelColor: '#0a2d6b',
        specialStateColor: '#1a4a9a',
        errorBkgColor: '#fee2e2',
        errorTextColor: '#991b1b',
      },
      class: {
        classText: '#0a2d6b',
        fillType0: '#e8eef8',
        fillType1: '#e8f0ff',
        fillType2: '#edf1fb',
        fillType3: '#d8e4f4',
        fillType4: '#c8d8f0',
        fillType5: '#b8cce8',
        fillType6: '#a8c0e0',
        fillType7: '#98b4d8',
      },
      gantt: {
        sectionBkgColor: '#eef2fc',
        altSectionBkgColor: '#f5f8ff',
        taskBorderColor: '#0a2d6b',
        taskBkgColor: '#e8eef8',
        taskTextColor: '#0a2d6b',
        taskTextLightColor: '#0a2d6b',
        taskTextDarkColor: '#0a2d6b',
        taskTextOutsideColor: '#0a2d6b',
        activeTaskBorderColor: '#0a2d6b',
        activeTaskBkgColor: '#c8d8f0',
        doneTaskBkgColor: '#94a3b8',
        doneTaskBorderColor: '#64748b',
        critBkgColor: '#fee2e2',
        critBorderColor: '#ef4444',
        todayLineColor: '#1a4a9a',
      },
      git: {
        git0: '#0a2d6b',
        git1: '#1a4a9a',
        git2: '#2a5aaa',
        git3: '#3a6aba',
        git4: '#4a7aca',
        git5: '#5a8ada',
        git6: '#1a3a8a',
        git7: '#0a2d6b',
        gitBranchLabel0: '#ffffff',
        gitBranchLabel1: '#ffffff',
        gitBranchLabel2: '#ffffff',
        gitBranchLabel3: '#ffffff',
        gitBranchLabel4: '#000000',
        gitBranchLabel5: '#000000',
        gitBranchLabel6: '#ffffff',
        gitBranchLabel7: '#ffffff',
      },
      pie: {
        pie1: '#0a2d6b',
        pie2: '#1a4a9a',
        pie3: '#2a5aaa',
        pie4: '#3a6aba',
        pie5: '#4a7aca',
        pie6: '#5a8ada',
        pie7: '#1a3a8a',
        pie8: '#0a2d6b',
        pieTitleTextColor: '#0a2d6b',
        pieSectionTextColor: '#ffffff',
        pieStrokeColor: '#f5f8ff',
      },
      requirement: {
        requirementBackground: '#e8eef8',
        requirementBorderColor: '#0a2d6b',
        requirementTextColor: '#0a2d6b',
        relationColor: '#1a4a9a',
        relationLabelBackground: '#f0f4ff',
        relationLabelColor: '#0a2d6b',
      },
      quadrant: {
        quadrant1Fill: '#e8eef8',
        quadrant2Fill: '#d8e4f4',
        quadrant3Fill: '#eef2fc',
        quadrant4Fill: '#f0f4ff',
        quadrant1TextFill: '#0a2d6b',
        quadrant2TextFill: '#0a2d6b',
        quadrant3TextFill: '#0a2d6b',
        quadrant4TextFill: '#0a2d6b',
        quadrantPointFill: '#0a2d6b',
        quadrantPointTextFill: '#ffffff',
        quadrantXAxisTextFill: '#0a2d6b',
        quadrantYAxisTextFill: '#0a2d6b',
        quadrantTitleFill: '#0a2d6b',
      },
      architecture: {
        archEdgeColor: '#1a4a9a',
        archEdgeArrowColor: '#1a4a9a',
        archGroupBorderColor: '#0a2d6b',
      },
      journey: {
        cScale0: '#e8eef8',
        cScale1: '#d8e4f4',
        cScale2: '#c8d8f0',
        cScale3: '#b8cce8',
        cScale4: '#a8c0e0',
        cScale5: '#98b4d8',
        cScale6: '#88a8d0',
        cScale7: '#789cc8',
        cScale8: '#6890c0',
        cScale9: '#5884b8',
        cScale10: '#4878b0',
        cScale11: '#386ca8',
      },
    },
  },
}
